import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Header from 'components/Header/Header'
import { ContentfulPreviewProvider } from 'components/contentful/contentful-preview-provider'
import { draftMode } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const { isEnabled } = draftMode()

	return (
		<html lang="es">
			<body className={inter.className}>
				<ContentfulPreviewProvider
					locale="es"
					enableInspectorMode={isEnabled}
					enableLiveUpdates={isEnabled}
				>
					<Header />
					{children}
				</ContentfulPreviewProvider>
			</body>
		</html>
	)
}
