import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Header from 'components/Header/Header'
import { ContentfulPreviewProvider } from 'components/contentful/contentful-preview-provider'
import { draftMode } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	robots: 'noindex, nofollow', // TODO: Remove for production
}

export async function generateStaticParams() {
	return [{ lang: 'es' }, { lang: 'en' }]
}

export default function RootLayout({
	children,
	params,
}: Readonly<{
	params: { lang: string }
	children: React.ReactNode
}>) {
	const { isEnabled } = draftMode()

	return (
		<html lang={params.lang}>
			<body className={inter.className}>
				<ContentfulPreviewProvider
					locale={params.lang}
					enableInspectorMode={isEnabled}
					enableLiveUpdates={isEnabled}
				>
					<Header />
					{children}
				</ContentfulPreviewProvider>
				<div id="experience-popup" />
			</body>
		</html>
	)
}
